### ISSUE TITLE
testing gitter (sorry peter)

### ISSUE THREAD

**Issue by nickrobson** [DownsideUp/AntiDrops#1]
hello

**Comment by peterarenot** [comment]
No worries. I’m just doing maths anyway. This is a welcome distraction.

**Comment by nickrobson** [comment]
potato potato potato

**Comment by nickrobson** [comment]
(I'm writing a Java API for Gitter, so that's why there's this spam)

**Comment by nickrobson** [comment]
thanks https://gist.github.com/nickrobson/5de5a7f4431cac758fe6
